---
version: '3'

services:
  odin:
    image: "massardtheo/odin:latest"
    environment:
      ODIN_SLEEP_DURATION: 20
  prom:
    image: "prom/prometheus:v2.16.0"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  grafana:
    image: "grafana/grafana:6.6.2"
    depends_on:
      - prom
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/:/etc/grafana/provisioning/"
      - "./grafana.ini:/etc/grafana/grafana.ini:ro"
