---
global:
  evaluation_interval: 1m
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: odin metrics
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - odin:8000
